fix_version: 4.4
dlm: '|'
tag_dict: 
  Account: 1
  AdvId: 2
  AdvRefID: 3
  AdvSide: 4
  AdvTransType: 5
  AllocAccount: 79
  AllocID: 70
  AllocRejCode: 88
  AllocShares: 80
  AllocStatus: 87
  AllocTransType: 71
  AvgPrxPrecision: 74
  AvgPx: 6
  BeginSeqNo: 7
  BeginString: 8
  BidPx: 132
  BidSize: 134
  BodyLength: 9
  BrokerOfCredit: 92
  CheckSum: 10
  ClientID: 109
  ClOrdID: 11
  Commission: 12
  CommType: 13
  CumQty: 14
  Currency: 15
  CxlQty: 84
  CxlRejReason: 102
  CxlType: 125
  DeliverToCompID: 128
  DeliverToSubID: 129
  DKReason: 127
  DlvyInst: 86
  EmailType: 94
  EncryptMethod: 98
  EndSeqNo: 16
  ExDestination: 100
  ExecBroker: 76
  ExecID: 17
  ExecInst: 18
  ExecRefID: 19
  ExecTransType: 20
  ExpireTime: 126
  ForexReq: 121
  FutSettDate: 64
  GapFillFlag: 123
  HandlInst: 21
  HeartBtInt: 108
  IDSource: 22
  IOIid: 23
  IOINaturalFlag: 130
  IOIOthSvc: 24
  IOIQltyInd: 25
  IOIQualifier: 104
  IOIRefID: 26
  IOIShares: 27
  IOITransType: 28
  Issuer: 106
  LastCapacity: 29
  LastMkt: 30
  LastPx: 31
  LastShares: 32
  LinesOfText: 33
  ListExecInst: 69
  ListID: 66
  ListNoOrds: 68
  ListSeqNo: 67
  LocateReqd: 114
  MaxFloor: 111
  MinQty: 110
  MiscFeeAmt: 137
  MiscFeeCurr: 138
  MiscFeeType: 139
  MsgSeqNum: 34
  MsgType: 35
  NetMoney: 118
  NewSeqNo: 36
  NoAllocs: 78
  NoDlvyInst: 85
  NoExecs: 124
  NoMiscFees: 136
  NoOrders: 73
  NoRpts: 82
  OfferPx: 133
  OfferSize: 135
  OnBehalfOfCompID: 115
  OnBehalfOfSubID: 116
  OpenClose: 77
  OrderID: 37
  OrderQty: 38
  OrdRejReason: 103
  OrdStatus: 39
  OrdType: 40
  OrigClOrdID: 41
  OrigSendingTime: 122
  OrigTime: 42
  PossDupFlag: 43
  PossResend: 97
  PrevClosePx: 140
  Price: 44
  ProcessCode: 81
  QuoteID: 117
  QuoteReqID: 131
  RawData: 96
  RawDataLength: 95
  RefAllocID: 72
  RefSeqNum: 45
  RelatdSym: 46
  ReportToExch: 113
  RptSeq: 83
  Rule80A: 47
  SecureData: 91
  SecureDataLen: 90
  SecurityDesc: 107
  SecurityID: 48
  SenderCompID: 49
  SenderSubID: 50
  SendingDate: 51
  SendingTime: 52
  SettlCurrAmt: 119
  SettlCurrency: 120
  SettlmntTyp: 63
  Shares: 53
  Side: 54
  Signature: 89
  SignatureLength: 93
  StopPx: 99
  Symbol: 55
  SymbolSfx: 65
  TargetCompID: 56
  TargetSubID: 57
  TestReqID: 112
  Text: 58
  TimeInForce: 59
  TradeDate: 75
  TransactTime: 60
  Urgency: 61
  ValidUntilTime: 62
  WaveNo: 105
msg_dict:
  Advertisement: 7
  AllocationInstruction: J
  AllocationInstructionAck: P
  AllocationReport: AS
  AllocationReportAck: AT
  AssignmentReport: AW
  BidRequest: k
  BidResponse: l
  BusinessMessageReject: j
  CollateralAssignment: AY
  CollateralInquiry: BB
  CollateralInquiryAck: BG
  CollateralReport: BA
  CollateralRequest: AX
  CollateralResponse: AZ
  Confirmation: AK
  ConfirmationAck: AU
  ConfirmationRequest: BH
  CrossOrderCancel/ReplaceRequest: t
  CrossOrderCancelRequest: u
  DerivativeSecurityList: AA
  DerivativeSecurityListRequest: z
  Don'tKnowTrade: Q
  Email: C
  ExecutionReport: 8
  Heartbeat: 0
  IOI: 6
  ListCancelRequest: K
  ListExecute: L
  ListStatus: N
  ListStatusRequest: M
  ListStrikePrice: m
  Logon: A
  Logout: 5
  MarketData-IncrementalRefresh: X
  MarketDataRequest: V
  MarketDataRequestReject: Y
  MarketData-Snapshot/FullRefresh: W
  MassQuote: i
  MassQuoteAcknowledgement: b
  MultilegOrderCancel/Replace: AC
  NetworkCounterpartySystemStatusRequest: BC
  NetworkCounterpartySystemStatusResponse: BD
  NewOrderCross: s
  NewOrderList: E
  NewOrderMultileg: AB
  NewOrderSingle: D
  News: B
  OrderCancel/ReplaceRequest: G
  OrderCancelReject: 9
  OrderCancelRequest: F
  OrderMassCancelReport: r
  OrderMassCancelRequest: q
  OrderMassStatusRequest: AF
  OrderStatusRequest: H
  PositionMaintenanceReport: AM
  PositionMaintenanceRequest: AL
  PositionReport: AP
  Quote: S
  QuoteCancel: Z
  QuoteRequest: R
  QuoteRequestReject: AG
  QuoteResponse: AJ
  QuoteStatusReport: AI
  QuoteStatusRequest: a
  RegistrationInstructions: o
  RegistrationInstructionsResponse: p
  Reject: 3
  RequestForPositions: AN
  RequestforPositionsAck: AO
  ResendRequest: 2
  RFQRequest: AH
  SecurityDefinition: d
  SecurityDefinitionRequest: c
  SecurityList: y
  SecurityListRequest: x
  SecurityStatus: f
  SecurityStatusRequest: e
  SecurityTypeRequest: v
  SecurityTypes: w
  SequenceReset: 4
  SettlementInstructionRequest: AV
  SettlementInstructions: T
  TestRequest: 1
  TradeCaptureReport: AE
  TradeCaptureReportAck: AR
  TradeCaptureReportRequest: AD
  TradeCaptureReportRequestAck: AQ
  TradingSessionStatus: h
  TradingSessionStatusRequest: g
  UserRequest: BE
  UserResponse: BF
  XMLMessage: n
